"""add subject assignment

Revision ID: 237ba4417f7d
Revises: 62d225019a3b
Create Date: 2026-08-09 22:52:47.914407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237ba4417f7d'
down_revision: Union[str, Sequence[str], None] = '62d225019a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_assignment', sa.Column('school_class_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subject_assignment', 'school_class', ['school_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_assignment', type_='foreignkey')
    op.drop_column('subject_assignment', 'school_class_id')
    # ### end Alembic commands ###
